version: "3"
services:
  opensearch:
    image: rps-os
    container_name: opensearch
    environment:
      - OPENAI_API_KEY
      # To help with debugging issues with opensearch starting.
      - DEBUG
      - NOEXIT
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - os-net
    volumes:
      - rpsos:/usr/share/opensearch/data
  rps:
    image: rps
    container_name: rps
    ports:
      - 2796:2796
    networks:
      - os-net
    environment:
      - SSL_HOSTNAME=rps
networks:
  os-net:
volumes:
  rpsos:
