- debug:
    processors:
      - debug-response:
          prefix: "in debug processor"
      - debug-response:
          prefix: "in second debug processor"
      - debug-response:
- dedup:
    processors:
      - dedup-response:
          threshold: 0.4
